[project]
name = "tyrannis"
version = "0.1.0a2"
description = "Flexible optimization framework for particle-based population algorithms, supporting diverse search spaces, optimization strategies, and execution backends."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Samuel Carlos Pessoa Oliveira" }
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Mathematics",
]

keywords = [
    "optimization",
    "metaheuristics",
    "population-based optimization",
    "particle-based optimization",
    "swarm intelligence",
    "particle swarm optimization",
    "PSO",
    "artificial bee colony optimization",
    "ABC",
    "parallel optimization",
    "distributed optimization",
    "island model",
    "mixed search space",
]


requires-python = ">=3.11,<=3.14"
dependencies = [
    "numpy>=2.1.3,<3.0.0",
    "scipy>=1.15.3,<2.0.0",
    "cloudpickle>=3.0.0,<4.0.0",
    "joblib>=1.4.2,<2.0.0",
]

[project.optional-dependencies]
cache = [
    "cachetools>=5.5.1",
]

spark = [
    "pyspark>=4.1.3",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
]

# mpi = [
#     "mpi4py>=4.1.2",
# ]

# ray = [ #Future implementation
#     "ray>=2.58.0",
# ]

# dask = [ #Future implementation
#     "dask>=2026.8.0",
#     "distributed>=2026.8.0",
# ]

[project.urls]
# Homepage = "https://github.com/<user>/tyrannis"
Repository = "https://github.com/renard162/tyrannis_optimizer"
# Documentation = "https://<user>.github.io/tyrannis"
Issues = "https://github.com/renard162/tyrannis_optimizer/issues"


[project.scripts]
tyrannis = "tyrannis:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "coverage>=7.16.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
testpaths = [
    "tests/unit",
    "tests/integration",
]
pythonpath = ["tests"]
addopts = "--import-mode=importlib"
# addopts = "--import-mode=importlib --cov=tyrannis --cov-report=term-missing"

[tool.coverage.run]
branch = true
omit = [
    "src/tyrannis/examples/*",
]
