import json
from abc import ABC, abstractmethod
from dataclasses import dataclass
from time import sleep

import numpy as np

from ...algorithm.base import AlgorithmBase


@dataclass
class StatusVariables:
    departure_particle_id: str
    departure_particle_data: str

    population: dict[str, float | None]
    actual_iter: int = -1

    best_particle_data: str = ""
    best_particle_fitness: float | None = None
    worst_particle_data: str = ""
    worst_particle_fitness: float | None = None


@dataclass
class ControlVariables:
    arrival_particle_id: str | None = None
    arrival_particle_var: dict[str, float] | None = None
    arrival_particle_fit: float | None = None

    iter_until: int | None = None

    def load_new_particle(self, particle_data: str) -> None:
        """
        Load a particle from its serialized representation.

        The particle data must be a string generated by the particle's
        `dump` method. The particle identifier, variables, and fitness are
        loaded into the corresponding control variables.
        """
        data = json.loads(particle_data)
        self.arrival_particle_id = data["identifier"]
        self.arrival_particle_var = data["variables"]
        self.arrival_particle_fit = data["fitness"]


class ProcessorBase(ABC):
    """Base class for processor agent."""

    def __init__(
        self,
        identifier: str,
        algorithm: AlgorithmBase,
        n_iter: int,
        n_particles: int,
    ) -> None:
        """
        Initialize the processor with an optimization algorithm.

        The processor must maintain a `stop_signal` control variable whose
        implementation provides an `is_set` method that returns `True` when
        the signal is active and `False` otherwise. The signal must also
        provide `set` and `clear` methods, where `set` activates the signal
        and `clear` deactivates it.

        The implementation of the signal is determined by the processor
        execution strategy. For example, a multiprocessing-based processor
        may use `multiprocessing.Event`, while a serial processor may use a
        compatible implementation without requiring the multiprocessing
        package.

        The provided algorithm is stored by the processor and is responsible
        for the optimization logic executed by the processor.

        Implement the class-specific __init__ (including the stop_signal
        implementation) and call the ProcessorBase initializer via super().
        """
        self._identifier = identifier
        self._n_iter = n_iter
        self._algorithm = algorithm
        self._init_particles(n_particles)
        self._control = ControlVariables()
        self._status = StatusVariables(
            population={},
            departure_particle_id="",
            departure_particle_data="",
        )

    def _init_particles(self, n_particles: int) -> None:
        for p_idx in range(n_particles):
            self._algorithm.create_particle(
                identifier=f"island:{self._identifier}|particle:{p_idx}",
                variables=None,
                fitness=None,
            )

    def wait_sync(self, actual_iter: int) -> None:
        if self._control.iter_until is None:
            return

        while actual_iter >= self._control.iter_until:
            sleep(0.01)

    def migration_control(self) -> None:
        self._insert_arrival_particle()
        self._departure_particle()

    def _insert_arrival_particle(self) -> None:
        if self._control.arrival_particle_id is None:
            return

        if self._control.arrival_particle_id not in self._algorithm.population:
            self._algorithm.create_particle(
                identifier=self._control.arrival_particle_id,
                variables=self._control.arrival_particle_var,
                fitness=self._control.arrival_particle_fit,
            )

    def _departure_particle(self) -> None:
        """
        Remove a departing particle from the algorithm population.

        This method will be implemented after the interaction methods
        between optimization islands have been defined.
        """
        return

    def update_iter_counter(self, actual_iter: int) -> None:
        self._status.actual_iter = actual_iter

    def update_status(self) -> None:
        self._update_population_status()
        self._update_partial_result()

    def _update_partial_result(self) -> None:
        if (self._algorithm.local_best is None) or (
            self._algorithm.local_worst is None
        ):
            return
        self._status.best_particle_fitness = self._algorithm.local_best.fitness
        self._status.best_particle_data = self._algorithm.local_best.dump()
        self._status.worst_particle_fitness = self._algorithm.local_worst.fitness
        self._status.worst_particle_data = self._algorithm.local_worst.dump()

    def _update_population_status(self) -> None:
        self._status.population = {
            p_id: p.fitness for p_id, p in self._algorithm.population.items()
        }

    @abstractmethod
    def run(self) -> None:
        """
        Execute the algorithm iterations.

        The iteration loop must run `actual_iter` from 0 through `self._n_iter`,
        inclusive. Iteration 0 represents the initial execution required to
        establish the initial states of the algorithm and its particles and
        does not represent an actual optimization iteration.

        The iteration flow must use `iter_until` as a synchronization
        control, preventing the processor from advancing beyond the
        iteration specified by this variable. The `stop_signal` control
        variable must be checked to allow the execution to be interrupted
        before subsequent iterations are performed.

        Before processing each iteration, the processor must call
        `insert_arrival_particle` to handle particles received from other
        processors and `remove_departure_particle` to handle particles that
        must leave the current population.

        The algorithm iteration must then be executed according to the
        algorithm's defined iteration lifecycle.
        """
