import json

from .backend import BackendBase


class ParallelBackendBase(BackendBase):
    """
    Base class for standalone parallel optimization backends.

    A parallel backend executes the optimization as a single island while
    delegating the parallel processing of its particles to the execution
    environment provided by the concrete backend.

    Unlike a distributed backend, this execution model has no concept of
    multiple islands, inter-island communication, migration, or
    `ProcessorBase`. The complete population belongs to a single optimization
    instance.

    The parallel backend does not contain an intermediate processor layer.
    The concrete backend submits particle processing to the parallel execution
    environment itself, while the cluster orchestrator, such as Spark or MPI,
    is responsible for distributing the computational workload among its
    workers.

    This differs from the distributed execution model, where the cluster
    orchestrator distributes the execution of processors and each
    `ProcessorBase`
    controls the optimization lifecycle of its own island. In a parallel
    backend, there is no processor controlling an island: the backend itself
    coordinates the execution and the external parallel runtime manages the
    distribution and scheduling of the computational work.

    The value of `n_particles` represents the complete initial population
    because this backend operates as a single island. The number of workers
    provided by the parallel execution environment does not change the
    population size.

    The backend integrates the optimization algorithm with the parallel
    execution environment. The algorithm remains responsible for defining
    the optimization lifecycle and the state transitions of its particles.
    The backend is responsible only for invoking the corresponding algorithm
    methods and executing particle-level operations through the parallel
    runtime.

    The general execution flow is:

        initialize_context
        -> init_particles
        -> loop:
            pre_iteration
            -> create_random_cache (new particles)
            -> initialize new particles in parallel
            -> create_random_cache (entire population)
            -> update particles in parallel
            -> pos_iteration
        -> update_result

    The methods involved in the optimization lifecycle, including
    `pre_iteration`, `create_random_cache`, `initialize_particle`,
    `update_particle`, and `pos_iteration`, belong to `AlgorithmBase`.
    Their behavior and state-transition rules are defined by the algorithm;
    this backend only invokes them according to the execution flow required
    by the optimization lifecycle.

    Particle initialization and particle updates may be executed concurrently
    by the concrete parallel execution environment. The backend must preserve
    the ordering and synchronization required between the algorithm lifecycle
    stages, while the cluster orchestrator is responsible for distributing
    and scheduling the actual computational work.

    The concrete backend defines how this parallel execution is implemented.
    For example, a Spark implementation may distribute particle operations
    through Spark tasks, while an MPI implementation may distribute them
    among MPI processes.

    The backend must preserve the behavioral contract of `AlgorithmBase`
    regardless of the underlying parallel execution mechanism.
    """

    def init_particles(self) -> None:
        """
        Create the initial population for the single optimization island.

        If the algorithm already contains particles, no particles are created.
        Otherwise, exactly `_n_particles` particles are created and registered
        in the algorithm.

        Particle identifiers are generated by the backend and must uniquely
        identify each particle within this optimization execution.

        Notes
        -----
        `n_particles` represents the complete initial population in a
        parallel backend because this backend operates as a single island.

        This method only creates the particle objects and registers them with
        the algorithm. Particle initialization, including the evaluation or
        establishment of their initial state, is performed later through the
        normal algorithm lifecycle.

        Concrete backends may override this method when their execution model
        requires a different mechanism for constructing the initial
        population, but the resulting algorithm state must remain equivalent.
        """
        if self._algorithm.population:
            return

        for p_idx in range(self._n_particles):
            self._algorithm.create_particle(
                identifier=f"{self._identifier}|particle:{p_idx}",
            )

    def update_result(self) -> None:
        """
        Store the best solution found by the single optimization island.

        The algorithm maintains its best particle in `local_best`. Since a
        parallel backend operates as a single island, this particle is already
        the global best result of the execution and no cross-island
        consolidation is required.

        The particle representation is serialized and converted into the
        backend result format, retaining only the fields defined by
        `_result_keys`.

        Notes
        -----
        If the algorithm has no local best, the backend does not create a
        result.

        This method performs result extraction only. It does not modify the
        algorithm population or its optimization state.
        """
        if self._algorithm.local_best is None:
            return

        self._result = json.loads(self._algorithm.local_best.dump())
